server:
  port: 8085

kafka:
  general:
    bootstrap-servers: localhost:9092
  stockAddedTopic:
    factory-service-topic: stockAddedTopic
  itemRequestTopic:
    warehouse-service-topic: itemRequestTopic

factory:
  replenish-interval-ms: 5000


#warehouse:
#  service:
#    url: http://localhost:8082/warehouse
