server:
  port: 8085

kafka:
  general:
    bootstrap-servers: localhost:9092

  itemRequest:
    topic: itemRequestTopic
    group-id: factoryGroup

  stockAdded:
    topic: stockAddedTopic

factory:
  replenish-interval-ms: 5000000

