server:
  port: 8083

# custom configuration via Configuration files
kafka:
  general:
    bootstrap-servers: localhost:9092

  ordersStatusUpdate:
    order-service-topic: orderServiceStatusUpdateTopic
    warehouse-service-topic: ordersStatusUpdateTopic
#    delivered-order-service-topic: deliveredOrderStatusUpdateTopic
    group-id: primaryGroup


warehouse:
  service:
    url: http://localhost:8084  # Updated to match the warehouse service port

# Camunda Cloud Configuration
camunda:
  client:
    optimize:
      base-url: https://lhr-1.optimize.camunda.io/70966460-4199-4643-a14f-64b0913ba8b7

    mode: saas

    cluster-id: 70966460-4199-4643-a14f-64b0913ba8b7
    region: lhr-1

    auth:
      client-id: jV_WrZ.Fk0xV4ijKOfGgTW7g59yTb8.Z
      client-secret: zPQYDeTnTPHkDKfdu9EP_rAfCKKr1jrFp34mbu1hu1k0vaPoRNC8Kp4C4uAHUYSg

    zeebe:
      base-url: https://70966460-4199-4643-a14f-64b0913ba8b7.lhr-1.zeebe.camunda.io:443

      # Operate API configuration
    operate:
      enabled: true
      base-url: https://lhr-1.operate.camunda.io/70966460-4199-4643-a14f-64b0913ba8b7

    # Tasklist API configuration
    tasklist:
      enabled: true
      base-url: https://lhr-1.tasklist.camunda.io/70966460-4199-4643-a14f-64b0913ba8b7

logging:
  level:
    io.camunda.zeebe.client.job.worker: ERROR
    io.grpc.stub.ClientCalls: ERROR